// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uZ6uOXZgPI6SdDg7KrWwjwkBFmiLSgM',
    appId: '1:510713230907:web:f9b42b4260dafebb3f4e1e',
    messagingSenderId: '510713230907',
    projectId: 'sneakersdb',
    authDomain: 'sneakersdb.firebaseapp.com',
    storageBucket: 'sneakersdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPYTRQL7rJSzdQVjyI98lP5dWE_qU9X2I',
    appId: '1:510713230907:android:11ab9a9ef6350b483f4e1e',
    messagingSenderId: '510713230907',
    projectId: 'sneakersdb',
    storageBucket: 'sneakersdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAguO2hap4KviKWvQQ4ZzoJ0LxOYxft_sw',
    appId: '1:510713230907:ios:33d1eee10b696c373f4e1e',
    messagingSenderId: '510713230907',
    projectId: 'sneakersdb',
    storageBucket: 'sneakersdb.appspot.com',
    iosBundleId: 'com.example.sneakersmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAguO2hap4KviKWvQQ4ZzoJ0LxOYxft_sw',
    appId: '1:510713230907:ios:33d1eee10b696c373f4e1e',
    messagingSenderId: '510713230907',
    projectId: 'sneakersdb',
    storageBucket: 'sneakersdb.appspot.com',
    iosBundleId: 'com.example.sneakersmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_uZ6uOXZgPI6SdDg7KrWwjwkBFmiLSgM',
    appId: '1:510713230907:web:254eb1027e83737a3f4e1e',
    messagingSenderId: '510713230907',
    projectId: 'sneakersdb',
    authDomain: 'sneakersdb.firebaseapp.com',
    storageBucket: 'sneakersdb.appspot.com',
  );
}
