// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEioyzuiNoh0ZpNLP7-yXjue1nFZYL0uk',
    appId: '1:571022700005:web:1bc9c2e2881a21dff6d30c',
    messagingSenderId: '571022700005',
    projectId: 'storesneaker',
    authDomain: 'storesneaker.firebaseapp.com',
    storageBucket: 'storesneaker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9MP7aDu3JD5khZLHcHki1fiqNcQvquEo',
    appId: '1:571022700005:android:c03b1fa3b9ae86a9f6d30c',
    messagingSenderId: '571022700005',
    projectId: 'storesneaker',
    storageBucket: 'storesneaker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-6gmGcAalYaZvdnk3D56kSYMvJViqC_E',
    appId: '1:571022700005:ios:e2f9df6419ac43e7f6d30c',
    messagingSenderId: '571022700005',
    projectId: 'storesneaker',
    storageBucket: 'storesneaker.appspot.com',
    iosBundleId: 'com.example.sneakersmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-6gmGcAalYaZvdnk3D56kSYMvJViqC_E',
    appId: '1:571022700005:ios:e2f9df6419ac43e7f6d30c',
    messagingSenderId: '571022700005',
    projectId: 'storesneaker',
    storageBucket: 'storesneaker.appspot.com',
    iosBundleId: 'com.example.sneakersmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEioyzuiNoh0ZpNLP7-yXjue1nFZYL0uk',
    appId: '1:571022700005:web:f4063922d7910307f6d30c',
    messagingSenderId: '571022700005',
    projectId: 'storesneaker',
    authDomain: 'storesneaker.firebaseapp.com',
    storageBucket: 'storesneaker.appspot.com',
  );

}